USE plataformasalud;

INSERT INTO `plataformasalud`.`status` (`datecreatstatus`, `nomstatus`) VALUES ('2024-02-21', 'CREADO');
INSERT INTO `plataformasalud`.`tipdoc` (`datecreatetipdoc`, `detatipdoc`, `tipdoc`) VALUES ('2024-02-21', 'CEDULA DE CIUDADANIA', 'CC');
INSERT INTO `plataformasalud`.`ubicaciones` (`datecreatubic`, `detubica`, `nomubicaciones`, `estubica_fk_idstatus`) VALUES ('2024-02-21', 'RECUPERACION', 'REC', '1');
INSERT INTO `plataformasalud`.`habcami` (`dethab`, `fechacreahab`, `nomhab`, `esthab_fk_idstatus`, `ubicahab_idubica`) VALUES ('RECUPERACION CAMILLA 1', '2024-02-21', 'REC 1', '1', '1');
INSERT INTO `plataformasalud`.`cargo_user` (`datecreatcarguser`, `detcarguser`, `nomcarg`, `estado_carguser_idstatus`) VALUES ('2024-02-21', 'AUXILIAR ADMINISTRATIVO', 'AUXADM', '1');
INSERT INTO `plataformasalud`.`departamentos` (`coddep`, `datecreatdep`, `nomdep`, `estdep_fk_idstatus`) VALUES ('73', '2024-02-21', 'TOLIMA', '1');
INSERT INTO `plataformasalud`.`ciudades` (`codciu`, `datecreatciu`, `nomciu`, `depciu_fk_coddep`, `estciu_fk_idstatus`) VALUES ('73001', '2024-02-21', 'IBAGUE', '73', '1');
INSERT INTO `plataformasalud`.`dx` (`iddx`, `capdx`, `creatdatedx`, `descdx`, `edadmaxdx`, `edadmindx`, `nomdx`, `sexdx`, `estdx_fk_idstatus`) VALUES ('A000', 'A00', '2024-02-21', 'COLERA NO ESPECIFICA', '999', '0', 'COLERA', 'AMBOS', '1');
INSERT INTO `plataformasalud`.`tipeapb` (`datecreatypeapb`, `nomtipeapb`, `estyeapb_fk_idstatus`) VALUES ('2024-02-21', 'MEDICINA PREPAGADA', '1');
INSERT INTO `plataformasalud`.`eapb` (`contaceapb`, `datecreateapb`, `direapb`, `emaileapb`, `gerenteapb`, `nomeapb`, `esteapb_fk_idstatus`, `tipent_idtipeapb`) VALUES ('3108610210', '2024-02-21', 'MZ D CASA ', 'EMAIL@EMAIL.COM', 'GERENTE', 'COLSANITAS', '1', '1');
INSERT INTO `plataformasalud`.`orgdes` (`datecreatorgdes`, `detorgdes`, `nomorgdes`, `estorgdes_fk_idstatus`) VALUES ('2024-02-21', 'CIRUGIA', 'CX', '1');
INSERT INTO `plataformasalud`.`permission` (`datecreatperm`, `detperm`, `namperm`, `estperm_fk_idstatus`) VALUES ('2024-02-21', 'CREACION DE OBJETOS', 'CREAR', '1');
INSERT INTO `plataformasalud`.`rol` (`creatrol`, `desrol`, `nomrol`, `estrol_fk_idstatus`) VALUES ('2024-02-21', 'CIRUJANO PLASTICO', 'CIRPLA', '1');
INSERT INTO `plataformasalud`.`permrol` (`datecreatidpermrol`, `detpermrol`, `nompermrol`, `estpermrol_fk_idstatus`, `permrol_fk_idperm`, `rolpermrol_fk_idrol`) VALUES ('2024-02-21', 'CREACION DE PACIENTES', 'CREPAC', '1', '1', '1');
INSERT INTO `plataformasalud`.`tytemp` (`creadatetytemp`, `detytemp`, `nomtytemp`, `esttytemp_fk_idstatus`) VALUES ('2024-02-21', 'NOTA DE ENFERMERIA', 'NOTENF', '1');
INSERT INTO `plataformasalud`.`user` (`creatdateuser`, `docuser`, `emailuser`, `firstname`, `lastname`, `password`, `username`, `carguser_fk_idcarguser`, `estuser_fk_idstatus`, `roluser_fk_idrol`, `typeiduser_fk_idtipdoc`) VALUES ('2024-02-21', '93414046', 'EMAIL@EMAIL.COM', 'JULIO', 'SALCEDO', 'JSALCEDO', 'JSALCEDO', '1', '1', '1', '1');
INSERT INTO `plataformasalud`.`template` (`creatdatetemp`, `dettemp`, `nametemp`, `esttemp_fk_idstatus`, `typtemp_fk_idtytemp`, `usertemp_fk_iduser`) VALUES ('2024-02-21', 'ESTA PLANTILLA ES UNA PLANTILLA DE ENFERMERIA', 'NOTENF', '1', '1', '1');
INSERT INTO `plataformasalud`.`prestserv` (`dirprestserv`, `docprestserv`, `emailprestserv`, `fechacreaprestserv`, `nomprestserv`, `telprestserv`, `ciuprestserv_fk_codciu`, `estadoprestserv_fk_idstatus`, `tipdocprestserv_fk_idtipdoc`) VALUES ('BARRIO PEDREGAL', '93414046', 'EMAIL@EMAIL.COM', '2024-02-21', 'JS SOLUCIONES', '3108610210', '73001', '1', '1');
INSERT INTO `plataformasalud`.`tproc` (`datecreatypx`, `detproc`, `nomtproc`, `estypx_fk_idstatus`) VALUES ('2024-02-21', 'PROCEDIMIENTO QUIRURGICO', 'PXQX', '1');
INSERT INTO `plataformasalud`.`tproc` (`datecreatypx`, `detproc`, `nomtproc`, `estypx_fk_idstatus`) VALUES ('2024-02-21', 'LABORATORIO CLINICO', 'LBCL', '1');
INSERT INTO `plataformasalud`.`procexam` (`codpxex`, `datecreatpxex`, `nompxex`, `sexopxex`, `estadopxex_fk_idstatus`, `tpxex_idtproc`) VALUES ('853101', '2024-02-21', 'MAMOPLASTIA DE REDUCCION POR GINECOMASTIA', 'AMBOS', '1', '1');
INSERT INTO `plataformasalud`.`repleg` (`datecreaterepleg`, `docrepleg`, `emailrepleg`, `paperepleg`, `pnomrepleg`, `saperepleg`, `snomrepleg`, `idprestservrepleg_fk_idprestserv`, `statusrepleg_fk_idstatus`, `tipdocrepleg_fk_idtipdoc`) VALUES ('2024-02-21', '93414046', 'email@email.com', 'SALCEDO', 'JULIO', 'PELAEZ', 'ERNESTO', '1', '1', '1');
INSERT INTO `plataformasalud`.`tipanest` (`datecreatanest`, `desctipanest`, `nomtipanest`, `esttypanest_idstatus`) VALUES ('2024-02-21', 'ANESTESIA GENERAL', 'ANEGRL', '1');
INSERT INTO `plataformasalud`.`typdx` (`datecreatypdx`, `detypdx`, `namtypdx`, `estyodx_fx_idstatus`) VALUES ('2024-02-21', 'DIAGNOSTICO PRINCIPAL', 'DXPR', '1');
INSERT INTO `plataformasalud`.`typdx` (`datecreatypdx`, `detypdx`, `namtypdx`, `estyodx_fx_idstatus`) VALUES ('2024-02-21', 'DIAGNOSTICO PREQUIRURGICO', 'DXPQ', '1');
INSERT INTO `plataformasalud`.`tynote` (`datecreatypnot`, `dettypnot`, `nametypnot`, `estypnot_fk_idstatus`) VALUES ('2024-02-21', 'NOTA ACLARATORIA', 'NTAC', '1');
INSERT INTO `plataformasalud`.`tipac` (`datecreatipac`, `nomtipac`, `esttippac_idstatus`) VALUES ('2024-02-21', 'COTIZANTE', '1');
